runtime: nodejs14

env:flex

#handlers:
  #- url: /
  #  static_files: public/index.html
   # upload: public/index.html

  #- url: /
    #static_dir: public

    skip_files:
  - (?!^public)

handlers:
  - url: /(.*\.(js|css|svg|png)(|\.map))$
  static_files: public/\1
  upload: public/(.*)(|\.map)
  - url: /.*
  static_files: public/index.html
  upload: public/.*
